CREATE TABLE /*$wgDBprefix*/patreon_user (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  patreon_id DECIMAL(25,0) unsigned NOT NULL,
  wikiuser_id int(10) unsigned NOT NULL,
  access_token TINYTEXT NOT NULL,
  refresh_token TINYTEXT NOT NULL,
  token_expires TIMESTAMP NOT NULL,
  name TINYTEXT NOT NULL,
  email TINYTEXT NOT NULL,
  discord TINYTEXT NOT NULL,
  tier TINYTEXT NOT NULL,
  status TINYTEXT NOT NULL,
  pledgeCadence TINYTEXT NOT NULL,
  note MEDIUMTEXT NOT NULL,
  lifetimePledgeCents INT(10) UNSIGNED NOT NULL DEFAULT 0,
  startDate DATETIME NOT NULL,
  lastPledgeDate DATETIME NOT NULL,
  addressName TINYTEXT NOT NULL,
  addressLine1 TINYTEXT NOT NULL,
  addressLine2 TINYTEXT NOT NULL,
  addressCity TINYTEXT NOT NULL,
  addressState TINYTEXT NOT NULL,
  addressZip TINYTEXT NOT NULL,
  addressCountry TINYTEXT NOT NULL,
  addressPhone TINYTEXT NOT NULL,
  shirtSize TINYTEXT NOT NULL,
  specialNote TINYTEXT NOT NULL,
  appCode TINYTEXT NOT NULL,
  KEY(patreon_id),
  KEY(wikiuser_id),
  KEY(appCode(20))
) /*$wgDBTableOptions*/;