CREATE TABLE /*$wgDBprefix*/patreon_shipment (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  patreon_id DECIMAL(25,0) unsigned NOT NULL,
  addressName TINYTEXT NOT NULL DEFAULT '',
  addressLine1 TINYTEXT NOT NULL DEFAULT '',
  addressLine2 TINYTEXT NOT NULL DEFAULT '',
  addressCity TINYTEXT NOT NULL DEFAULT '',
  addressState TINYTEXT NOT NULL DEFAULT '',
  addressZip TINYTEXT NOT NULL DEFAULT '',
  addressCountry TINYTEXT NOT NULL DEFAULT '',
  addressPhone TINYTEXT NOT NULL DEFAULT '',
  email TINYTEXT NOT NULL DEFAULT '',
  orderNumber TINYTEXT NOT NULL DEFAULT '',
  orderSku TINYTEXT NOT NULL DEFAULT '',
  orderQnt INT(10) NOT NULL DEFAULT 0,
  shipMethod TINYTEXT NOT NULL DEFAULT '',
  createDate TIMESTAMP NOT NULL,
  isProcessed TINYINT NOT NULL DEFAULT 0,
  KEY(patreon_id),
  KEY(orderNumber(16))
) /*$wgDBTableOptions*/;