CREATE TABLE /*$wgDBprefix*/patreon_user (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  patreon_id DECIMAL(25,0) unsigned NOT NULL,
  wikiuser_id int(10) unsigned NOT NULL DEFAULT 0,
  access_token TINYTEXT NOT NULL DEFAULT '',
  refresh_token TINYTEXT NOT NULL DEFAULT '',
  token_expires TIMESTAMP NOT NULL,
  name TINYTEXT NOT NULL DEFAULT '',
  email TINYTEXT NOT NULL DEFAULT '',
  discord TINYTEXT NOT NULL DEFAULT '',
  tier TINYTEXT NOT NULL DEFAULT '',
  status TINYTEXT NOT NULL DEFAULT '',
  pledgeCadence TINYTEXT NOT NULL DEFAULT '',
  note MEDIUMTEXT NOT NULL DEFAULT '',
  lifetimePledgeCents INT(10) UNSIGNED NOT NULL DEFAULT 0,
  startDate DATETIME NOT NULL,
  lastPledgeDate DATETIME NOT NULL,
  addressName TINYTEXT NOT NULL DEFAULT '',
  addressLine1 TINYTEXT NOT NULL DEFAULT '',
  addressLine2 TINYTEXT NOT NULL DEFAULT '',
  addressCity TINYTEXT NOT NULL DEFAULT '',
  addressState TINYTEXT NOT NULL DEFAULT '',
  addressZip TINYTEXT NOT NULL DEFAULT '',
  addressCountry TINYTEXT NOT NULL DEFAULT '',
  addressPhone TINYTEXT NOT NULL DEFAULT '',
  shirtSize TINYTEXT NOT NULL DEFAULT '',
  specialNote TINYTEXT NOT NULL DEFAULT '',
  appCode TINYTEXT NOT NULL DEFAULT '',
  KEY(patreon_id),
  KEY(wikiuser_id),
  KEY(appCode(20))
) /*$wgDBTableOptions*/;